apiVersion: v2
appVersion: 1.23.0
description: Helm chart for deploying Istio operator
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- operator
name: istio-operator
sources:
- https://github.com/istio/istio/tree/master/operator
version: 1.23.0
