apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.giropopsSenhas.service.name }}
  labels:
    app: {{ .Values.giropopsSenhas.labels.app }}
spec:
  selector:
    app: {{ .Values.giropopsSenhas.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.giropopsSenhas.service.port }}
      targetPort: {{ .Values.giropopsSenhas.service.targetPort }}
      name: {{ .Values.giropopsSenhas.service.name }}
  type: {{ .Values.giropopsSenhas.service.type }}
